name: Build check on PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 18.16.0

    - name: Install dependencies in client app
      working-directory: .
      run: npm install

    - name: Build NextJs
      working-directory: .
      run: |
        npm run build
        